apiVersion: v1
kind: Service
metadata:
  name: project-app
  labels:
    app: project-app
spec:
  type: NodePort
  selector:
    app: spring
  ports:                      
  - name: http
    port: 8235
    targetPort: 8235
