apiVersion: v1
kind: Service
metadata:
  name: project-postgres
  labels:
    app: project-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:                       
    app: project-postgres
    tier: postgres
